### ISSUE TITLE
UI Issue: Need Fixed Dimension for Azure service summary dialog Screen.

### ISSUE THREAD

**Issue by leotilli** [MSOpenTech/msopentech-tools-for-intellij#38] opened 2014-11-28 17:24 UTC
Currently Azure service summary dialog screen shows as below.
![image](https://cloud.githubusercontent.com/assets/7380916/5027985/68d3f31e-6b5b-11e4-9e80-922e74b47ff0.png).So it needs Fixed  Dimension for Azure service summary dialog Screen.
This issue is  reproducible in  IntelliJ 14 IDE

**Comment by babumuralidharan** [comment] 2015-02-13 00:12
LGTM in Mac. @kasturiswain just check once from your end and close the issue

**Comment by kasturiswain** [comment] 2015-02-13 08:25
This issue is reproducible in windows/intelliJ14.0.3.
PFB the screen shot.
![uiissue](https://cloud.githubusercontent.com/assets/10046647/6184451/d2025a82-b387-11e4-9923-e67546e5db59.png)

**Comment by leotilli** [comment] 2015-03-31 03:46
Unable to reproduce issue on Windows - IntelliJ 14.1

![image](https://cloud.githubusercontent.com/assets/1890830/6911985/4198fa6a-d73f-11e4-9631-a64904a39d64.png)

**Comment by kasturiswain** [comment] 2015-03-31 11:03
I am able to reproduce this issue in latest build in windows, IntelliJ 14.1.
PFB the screen shot.
![summary](https://cloud.githubusercontent.com/assets/10046647/6917588/91215e68-d7c3-11e4-857b-48ae0aae1416.png)

**Comment by kasturiswain** [comment] 2015-04-02 14:21
Not able to reproduce after changing the screen resolution.
PFB the screen shot.
![summary](https://cloud.githubusercontent.com/assets/10046647/6965789/a7aeff5a-d971-11e4-9cde-6af01500c003.png)

**Closed by kasturiswain** 2015-04-02 14:21 UTC
Labels: bug, cannot reproduce, review to close
