### ISSUE TITLE
Multiple subscriptions

### ISSUE THREAD

**Issue by bilekt3** [MSOpenTech/msopentech-tools-for-intellij#371] opened 2015-07-27 15:33 UTC
If you have more subscriptions resource list is messy because you are unable to distinguish what service run under which account.

Something like (Subscription) might help...

More on attached image

![screen shot 2015-07-27 at 17 32 01](https://cloud.githubusercontent.com/assets/381740/8910152/75775d1a-3485-11e5-81a7-71e06dd7e2da.png)

**Comment by ramkumargtv** [comment] 2015-09-08 15:07
Issue is still there and there is no way by which one can distinguish which service is under which account .

**Comment by BeatriceOltean** [comment] 2015-09-09 18:10
You can filter the subscriptions in the Manage Subscriptions window and the Explorer will update based on your selection

**Comment by martinsawicki** [comment] 2016-02-01 23:20
based on Beatrice's comment, resolving as by design.

**Closed as completed by martinsawicki** 2016-02-01 23:20 UTC
