### ISSUE TITLE
NullPointerException occurs if you close Azure AD interactive auth browser window

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#201] opened 2015-02-19 19:46 UTC
You get the following error if you close the Azure AD interactive authentication browser window (by clicking the close button on the top right corner) instead of signing in.

![image](https://cloud.githubusercontent.com/assets/628128/6274482/cfd2e0c0-b82c-11e4-98db-578eeeb80cac.png)

And if you open the _Manage Subscriptions_ dialog after that you get the following error:

![image](https://cloud.githubusercontent.com/assets/628128/6274519/fdbfa234-b82c-11e4-8d68-18121986681e.png)

And then the _Manage Subscriptions_ dialog gets stuck in a message box loop. There's no way to exit the dialog without signing in or importing a subscription unless you terminate the IDE process.

**Comment by BeatriceOltean** [comment] 2015-03-20 18:14
Kasturi, would you please check to see if it is still reproducible?

**Comment by kasturiswain** [comment] 2015-03-23 06:25
This error is still reproducible.

**Comment by leotilli** [comment] 2015-03-31 04:21
Unable to reproduce, on Windows - IntelliJ.

I've tried the following
-Bring Up the Manage Subscriptions Form (from Service Explorer, Azure Activity Wizard, or Create VM Wizard)
-Click to Sign in
-Close the Explorer PopUp
-Got back to Manage Subscription Form, without errors, no subscriptions loaded.

Could you provide us detailed instructions of the steps you perform.
Are you selecting or clearing 'keep me signed in' at any time?

**Comment by kasturiswain** [comment] 2015-03-31 07:07
I was able to reproduce this previously when the sign in option was asking for more than one windows for sign in and I closed one of the window of "Sign in".
Now only one window is asking for sign in and when I am closing the particular window, I am not able to reproduce this issue.
Closing this issue.

**Closed as completed by kasturiswain** 2015-03-31 07:07 UTC
Labels: Pri1, review to close, cannot reproduce
