### ISSUE TITLE
Filesystem permission errors from plugin when starting IntelliJ IDEA

### ISSUE THREAD

**Issue by codebrewer** [MSOpenTech/msopentech-tools-for-intellij#104] opened 2015-01-20 08:37 UTC
I installed plugin version 0.1.74 into IntelliJ IDEA IU-139.1038.6 (the latest 14.0.3 EAP at time of writing) on OS X 10.10.1 (Yosemite) but see the following errors reported on startup:

> Error: 0:225: execution error:
> cp: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity: Permission denied
> cp: /var/folders/25/5txsgx3s6zb1h_blj5r7m2pr0000gp/T/TempAzure/MobileServiceTemplate/AzureServicesActivity: unable to copy extended attributes to /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity: No such file or directory
> cp: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/globals.xml.ftl: No such file or directory
> cp: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/recipe.xml.ftl: No such file or directory
> cp: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root: No such file or directory
> cp: /var/folders/25/5txsgx3s6zb1h_blj5r7m2pr0000gp/T/TempAzure/MobileServiceTemplate/AzureServicesActivity/root: unable to copy extended attributes to /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root: No such file or directory
> cp: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/AndroidManifest.xml.ftl: No such file or directory
> cp: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/res: No such file or directory
> cp: /var/folders/25/5txsgx3s6zb1h_blj5r7m2pr0000gp/T/TempAzure/MobileServiceTemplate/AzureServicesActivity/root/res: unable to copy extended attributes to /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/res: No such file or directory
> cp: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/res/values: No such file or directory
> cp: /var/folders/25/5txsgx3s6zb1h_blj5r7m2pr0000gp/T/TempAzure/MobileServiceTemplate/AzureServicesActivity/root/res/values: unable to copy extended attributes to /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/res/values: No such file or directory
> cp: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/res/values/strings.xml.ftl: No such file or directory
> cp: utimes: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/res/values: No such file or directory
> cp: chown: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/res/values: No such file or directory
> cp: chmod: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/res/values: No such file or directory
> cp: chflags: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/res/values: No such file or directory
> cp: /var/folders/25/5txsgx3s6zb1h_blj5r7m2pr0000gp/T/TempAzure/MobileServiceTemplate/AzureServicesActivity/root/res/values: unable to copy ACL to /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/res/values: No such file or directory
> cp: utimes: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/res: No such file or directory
> cp: chown: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/res: No such file or directory
> cp: chmod: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/res: No such file or directory
> cp: chflags: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/res: No such file or directory
> cp: /var/folders/25/5txsgx3s6zb1h_blj5r7m2pr0000gp/T/TempAzure/MobileServiceTemplate/AzureServicesActivity/root/res: unable to copy ACL to /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/res: No such file or directory
> cp: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/src: No such file or directory
> cp: /var/folders/25/5txsgx3s6zb1h_blj5r7m2pr0000gp/T/TempAzure/MobileServiceTemplate/AzureServicesActivity/root/src: unable to copy extended attributes to /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/src: No such file or directory
> cp: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/src/app_package: No such file or directory
> cp: /var/folders/25/5txsgx3s6zb1h_blj5r7m2pr0000gp/T/TempAzure/MobileServiceTemplate/AzureServicesActivity/root/src/app_package: unable to copy extended attributes to /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/src/app_package: No such file or directory
> cp: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/src/app_package/AzureServiceActivity.java.ftl: No such file or directory
> cp: utimes: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/src/app_package: No such file or directory
> cp: chown: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/src/app_package: No such file or directory
> cp: chmod: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/src/app_package: No such file or directory
> cp: chflags: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/src/app_package: No such file or directory
> cp: /var/folders/25/5txsgx3s6zb1h_blj5r7m2pr0000gp/T/TempAzure/MobileServiceTemplate/AzureServicesActivity/root/src/app_package: unable to copy ACL to /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/src/app_package: No such file or directory
> cp: utimes: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/src: No such file or directory
> cp: chown: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/src: No such file or directory
> cp: chmod: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/src: No such file or directory
> cp: chflags: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/src: No such file or directory
> cp: /var/folders/25/5txsgx3s6zb1h_blj5r7m2pr0000gp/T/TempAzure/MobileServiceTemplate/AzureServicesActivity/root/src: unable to copy ACL to /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root/src: No such file or directory
> cp: utimes: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root: No such file or directory
> cp: chown: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root: No such file or directory
> cp: chmod: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root: No such file or directory
> cp: chflags: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root: No such file or directory
> cp: /var/folders/25/5txsgx3s6zb1h_blj5r7m2pr0000gp/T/TempAzure/MobileServiceTemplate/AzureServicesActivity/root: unable to copy ACL to /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/root: No such file or directory
> cp: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/template.xml: No such file or directory
> cp: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity/template_azure_services_activity.png: No such file or directory
> cp: utimes: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity: No such file or directory
> cp: chown: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity: No such file or directory
> cp: chmod: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity: No such file or directory
> cp: chflags: /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity: No such file or directory
> cp: /var/folders/25/5txsgx3s6zb1h_blj5r7m2pr0000gp/T/TempAzure/MobileServiceTemplate/AzureServicesActivity: unable to copy ACL to /Applications/IntelliJ IDEA 14 EAP.app/Contents/plugins/android/lib/templates/activities/AzureServicesActivity: Permission denied (1)

The user account under which I run IntelliJ IDEA is not the user account used for installation so has no permissions to modify the installation.

Is it actually necessary to install files into the host application?

Thanks for the plugin - I was really pleased to find Azure tooling for my favourite IDE :clap:

**Comment by akrakovsky** [comment] 2015-01-21 17:34
I sent a PR that fixes this issue. Thanks.

**Comment by codebrewer** [comment] 2015-01-21 22:11
Thanks for the quick attention this received!

Apologies, but I didn't make my point clearly in my original comment.  I wasn't so much reporting a need to elevate privileges to avoid the errors - it's more a question of the plugin trying to write to a location it (IMHO) shouldn't.

I was surprised to see a 3rd-party plugin modifying the host application (IntelliJ IDEA in my case) installation.  Personally, I'd say that's off limits.  After all, 3rd-party plugins themselves aren't installed into the host application location but (by default) somewhere under the user's home directory.

I see that the plugin's modifying the Android Support plugin that ships with IntelliJ IDEA.  Is that expected even though I'm not running Android Studio?  I don't know the plugin's history - maybe it started off targeting just Android Studio and this is a legacy of that?  I actually have the Android Support plugin disabled so if MSOpenTech Tools needs it to be enabled then it needs to declare a dependency on it.  Since there's no dependency declared maybe it just uses it as a location to store various templates and such?  If _that's_ the case then can't it store them local to its own installation location (_e.g._ in its own lib directory)?

Thanks again.

**Comment by BeatriceOltean** [comment] 2015-01-29 23:48
Dupe of issue #27

**Comment by avranju** [comment] 2015-01-30 02:59
@codebrewer Thanks for filing this. We're working on addressing the larger issue. It's just that the activity templates model in IntelliJ (and Android Studio) isn't quite as extensible as we'd like. Will update this issue once we have a resolution.

**Comment by babumuralidharan** [comment] 2015-02-16 20:36
This issue is fixed in latest release. Closing this for now.

**Comment by avranju** [comment] 2015-02-16 20:37
@codebrewer v0.1.102 from the JetBrains plugin repository should have this addressed. Thanks!

**Closed by babumuralidharan** 2015-02-16 20:36 UTC
Labels: bug, review to close
