### ISSUE TITLE
Pre-populate Notification Hub parameters in new Azure activity wizard

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#171] opened 2015-02-05 00:30 UTC
While the wizard for adding a new Azure Services Activity can pull your information for the Mobile Service, you’re still required to enter the information for your Hub manually. Consider pre-populating the fields automatically.

**Comment by BeatriceOltean** [comment] 2015-02-05 00:41
This is a dupe of 73rd and we have to further discuss with the Notification team regarding the Enhanced Push

**Closed by BeatriceOltean** 2015-02-05 00:41 UTC
Labels: bug
