### ISSUE TITLE
Service Explorer doesn't load - "Ambiguous sessions detected"

### ISSUE THREAD

**Issue by babumuralidharan** [MSOpenTech/msopentech-tools-for-intellij#284] opened 2015-05-07 02:23 UTC
Issue reported by @joshgav 

Not able to load my Azure Services Explorer, get the following error. Using Android Studio 1.2.
May be something funny with cached cookies or tokens?

```
java.lang.NullPointerException
    at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AuthTokenRequestFilter.filter(AuthTokenRequestFilter.java:55)
    at com.microsoft.windowsazure.core.pipeline.apache.HttpRequestInterceptorAdapter.process(HttpRequestInterceptorAdapter.java:42)
    at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:131)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:192)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
    at com.microsoft.windowsazure.management.compute.HostedServiceOperationsImpl.list(HostedServiceOperationsImpl.java:3687)
    at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerImpl.getHostedServices(AzureSDKManagerImpl.java:1331)
    at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerImpl.getVirtualMachines(AzureSDKManagerImpl.java:195)
    at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerADAuthDecorator$2.run(AzureSDKManagerADAuthDecorator.java:131)
    at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerADAuthDecorator$2.run(AzureSDKManagerADAuthDecorator.java:128)
    at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerADAuthDecorator.runWithRetry(AzureSDKManagerADAuthDecorator.java:51)
    at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerADAuthDecorator.getVirtualMachines(AzureSDKManagerADAuthDecorator.java:128)
    at com.microsoftopentechnologies.intellij.serviceexplorer.azure.vm.VMServiceModule.refreshItems(VMServiceModule.java:52)
    at com.microsoftopentechnologies.intellij.serviceexplorer.Node.refreshItems(Node.java:334)
    at com.microsoftopentechnologies.intellij.serviceexplorer.Node$BackgroundLoader.run(Node.java:424)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

![Failed login](https://cloud.githubusercontent.com/assets/4421720/7459125/ac71584e-f24e-11e4-9028-fc95dd6ee98d.png)
![Error message](https://cloud.githubusercontent.com/assets/4421720/7459126/ac814e3e-f24e-11e4-88fb-57b682e81bf8.png)
![Error message](https://cloud.githubusercontent.com/assets/4421720/7459127/ac8acaea-f24e-11e4-88e0-bfaae952dbc8.png)

**Comment by BeatriceOltean** [comment] 2015-05-26 17:21
Need repro steps

**Comment by omendrapandey** [comment] 2015-05-27 13:55
Couldn't reproduce the issue from my end .

**Comment by omendrapandey** [comment] 2015-06-23 14:10
Couldn't reproduce the issue .Closing it .

**Closed as completed by omendrapandey** 2015-06-23 14:10 UTC
Labels: Pri1
